#DATASOURCE
spring.datasource.url=jdbc:postgresql://dpg-d72j3uruibrs73bd1ep0-a.virginia-postgres.render.com:5432/workshop_rc1e
spring.datasource.username=devpostgres
spring.datasource.password=yKMbRDqoAWnPVfL59PRft3SAIzzVHy1s
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA, SQL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
